disabled_rules: # rule identifiers to exclude from running
  - colon
  - comma
  - trailing_whitespace
  - control_statement
#  - control_statement
#  - file_length
#  - force_cast
#  - force_try
#  - function_body_length
#  - leading_whitespace
#  - line_length
#  - nesting
#  - opening_brace
#  - operator_whitespace
#  - return_arrow_whitespace
#  - statement_position
#  - todo
#  - trailing_newline
#  - trailing_semicolon
#  - type_body_length
  - type_name
#  - variable_name_max_length
#  - variable_name_min_length
  - variable_name
  - valid_docs
opt_in_rules: # some rules are only opt-in
  - empty_count
#  - missing_docs
  # Find all the available rules by running:
  # swiftlint rules
included: # paths to include during linting. `--path` is ignored if present.
  - CBA


# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
# rules that have both warning and error levels, can set just the warning level
# implicitly
line_length: 310
# they can set both implicitly with an array
type_body_length:
  - 300 # warning
  - 400 # error
# or they can set both explicitly
file_length:
  warning: 500
  error: 1200
# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
# type_name:
#   min_length: 3 # only warning
#   max_length: # warning and error
#     warning: 40
#     error: 50
#   excluded: iPhone # excluded via string
# variable_name:
#   min_length: # only min_length
#     error: 3 # only error
#   excluded: # excluded via string array
#     - id
#     - URL
#     - GlobalAPIKey
#reporter: "csv" # reporter type (xcode, json, csv, checkstyle)
#Refer - https://swifting.io/blog/2016/03/29/11-swiftlint/
